### ISSUE TITLE
Bug Report: Game crashes when playing "Die Bastards"

### ISSUE THREAD

**Issue by BombasticTom** [nebulazorua/tails-gets-trolled-v3#4]
When "hide characters" setting is enabled, the game just crashes and reports "null object reference" when I start playing "Die Bastards". The option works for remixes. Didn't test for any other Story Mode song tho.

**Comment by BombasticTom** [comment]
idk if it helps, but I didn't try hiding the characters when the stage **isn't** hidden

**Comment by nebulazorua** [comment]
I've fixed it in the patch which is coming up soon

**Comment by BombasticTom** [comment]
> I've fixed it in the patch which is coming up soon

cool 👍
